# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: a Journey
email: cholun@outlook.com
description: > # this means to ignore newlines until "baseurl:"
    Hi, I am cholun, and this is my personal blog.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://cholun.github.io" # the base hostname & protocol for your site
twitter_username:
github_username:

gems: [jekyll-paginate]
paginate: 5
paginate_path: "/blog/page:num/"

# Build settings
markdown: kramdown

# Google services
google_analytics: UA-89538283-1